/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 sofa.gltf -types --transform 
Files: sofa.gltf [8.64MB] > sofa-transformed.glb [307.5KB] (96%)
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/margot-2-seater-sofa-old-rose-velvet-b3d693a003c94f4e989c08fe08c3af8c
Title: Margot 2 Seater Sofa, Old Rose Velvet
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_FLOOR_0: THREE.Mesh
    Margot_2_Seater_Sofa__Velvet_0: THREE.Mesh
    Margot_2_Seater_Sofa_Gold_0: THREE.Mesh
    Margot_2_Seater_Sofa_Wood_0: THREE.Mesh
  }
  materials: {
    FLOOR: THREE.MeshStandardMaterial
    Velvet: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

export function Sofa(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./sofa.gltf') as GLTFResult
  return (
    <group {...props} position={0} rotation={[0.5, -0.5, 0]} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane001_FLOOR_0.geometry} material={materials.FLOOR} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Margot_2_Seater_Sofa__Velvet_0.geometry} material={materials.Velvet} position={[-27.517, 0.417, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Margot_2_Seater_Sofa_Gold_0.geometry} material={materials.Gold} position={[-27.517, 0.417, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Margot_2_Seater_Sofa_Wood_0.geometry} material={materials.Wood} position={[-27.517, 0.417, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./sofa.gltf')
